name: Build Python to EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install PyInstaller
      run: pip install pyinstaller
      
    - name: Build EXE
      run: |
        cd src
        pyinstaller --onefile --console --name MyApp main.py
      
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable
        path: src/dist/MyApp.exe
